### ISSUE TITLE
Error al leer los datos de John Hopkins 

### ISSUE THREAD

**Issue by JuanCarlosSantiagoCulebras** [joscani/dashboard_cvirus#10]
Buenas Jose

Me da error al leer los datos iniciales, 

Error in open.connection(con, "rb") : HTTP error 404.

No se si han cambiado algo en el acceso a github o han modificado algo en el repositorio.

He probado, y cambiando a la url directa sin raw.githubusercontent.com y añadiendo "?raw=true" al final funciona.

urlc = 'https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv?raw=true'

cvirus_confirmed <- read_csv(urlc)

**Comment by joscani** [comment]
Gracias. 
Ya está arreglado.
