### ISSUE TITLE
Error en ccaa_longer$fecha <- as.Date

### ISSUE THREAD

**Issue by JuanCarlosSantiagoCulebras** [joscani/dashboard_cvirus#9]
Buenas José, gracias por el trabajo, me parece muy bueno.

Soy nuevo en contribuir en proyectos GitHub, me he bajado tu código para ver si puedo aportar algo. Pero al ejecutar me ha dado un error al pasar a fecha el campo en el Data Frame ccaa_longer.

No  se si han cambiado el formato en el fichero original, o es que yo tengo otra configuración, el caso es que he comentado la parte de la indicación de formato y ya me funciona.

ccaa_longer$fecha <- as.Date(as.character(ccaa_longer$fecha)) ##, format = "%d/%m/%y")

Un saludo.

**Comment by joscani** [comment]
Si justo habían cambiado el formato de fecha. Gracias. Ya está corregido en develop
